name: Test

on:
  push:
    tags:
      - "*"
# on:
#   pull_request:
#     types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: samifiaz/gh-action-docker@master
      env:
        AWS_S3_BUCKET: 's3 bucket name' # ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: 'access key id' #${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: 'access key' # ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'dist'      # optional: defaults to entire repository
