name: Test

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: ls
      - uses: samifiaz/gh-action-docker@master
        run: ls
